export const projects = [
    {
      title: "TableMate",
      description: "A full-stack QR code restaurant ordering system built from scratch. Customers can scan, order, and pay seamlessly.",
      tags: ["Full Stack", "Solo Project", "Bootcamp Capstone"],
      techStack: ["React", "JavaScript", "MongoDB", "REST APIs","Node.js", "Express.js", "Sass"],
      image: "/images/tablemate.png",
      github: "https://github.com/NicoleBiii/Table-Mate",
      Demo: "https://tablemate-demo.vercel.app",
    },
    {
      title: "AI News",
      description: "Hackathon project built with Google Gemini API to generate news discussion topics using AI.",
      tags: ["AI", "Hackathon"],
      techStack: ["React", "JavaScript", "REST APIs", "Google Gemini"],
      image: "/images/simplenews.png",
      github: "https://github.com/NicoleBiii/simple-news",
    },
    {
      title: "True North",
      description: "Collaborative Microsoft Hackathon site to check if brands are Canadian and suggest alternatives.",
      tags: ["Team Project", "API", "Hackathon"],
      techStack: ["React", "JavaScript", "MySQL", "Google Gemini"],
      image: "/images/truenorth.png",
      Demo: "https://instock-demo.vercel.app",
    },
    {
      title: "Instock",
      description: "Inventory management app built by 4-person team. I handled fuzzy search, attribute sorting, responsive UI and modals.",
      tags: ["Team Project", "Responsive", "Backend Logic"],
      techStack: ["React", "JavaScript", "MySQL", "Node.js", "Express.js"],
      image: "/images/instock.png",
      github: "https://github.com/olivia-onuk/instock-full-stack-attack",
      Demo: "https://instock-demo.vercel.app",
    },
  ];