export const projects = [
    {
      title: "TableMate",
      description: "Full-stack QR code restaurant ordering system with real-time updates and bilingual (EN/ZH) UI — built solo from scratch.",
      tags: ["Full Stack", "Solo Project", "Bootcamp Capstone"],
      techStack: ["React", "Node.js", "Express.js", "MongoDB", "WebSocket", "JWT", "Sass"],
      image: "/images/tablemate.png",
      github: "https://github.com/NicoleBiii/Table-Mate",
      responsibilities: [
        "Designed and built end-to-end: REST API, JWT auth, WebSocket for live order status updates",
        "Implemented QR-based ordering flow: scan → browse menu → place order → real-time confirmation",
        "Built bilingual (EN/ZH) UI with role-based access for customers and staff",
      ],
      videoUrl: "/videos/tablemate.MOV",
    },
    {
      title: "AI News",
      description: "Hackathon project using Google Gemini API to generate contextual discussion topics from live news.",
      tags: ["AI", "Hackathon"],
      techStack: ["React", "JavaScript", "Node.js", "Google Gemini API"],
      image: "/images/simplenews.png",
      github: "https://github.com/NicoleBiii/simple-news",
      responsibilities: [
        "Led frontend and backend development using React and Node.js",
        "Integrated Google Gemini API to auto-generate AI-powered discussion topics from news articles",
      ],
      videoUrl: "/videos/simplenews.mp4",
    },
    {
      title: "True North",
      description: "Microsoft Hackathon app that checks if brands are Canadian-owned and suggests local alternatives.",
      tags: ["Team Project", "Hackathon", "AI"],
      techStack: ["React", "JavaScript", "MySQL", "Google Gemini API"],
      image: "/images/truenorth.png",
      responsibilities: [
        "Built core frontend features and custom UI components in React",
        "Handled API integration and logic for brand validation and local alternative recommendations",
        "Collaborated cross-functionally with PMs and designers under hackathon time constraints",
      ],
      videoUrl: "/videos/truenorth.mp4",
    },
    {
      title: "InStock",
      description: "Warehouse management system built by a 4-person Agile team. Earned 98.5% project score.",
      tags: ["Agile", "Team Project", "Full Stack"],
      techStack: ["React", "Node.js", "Express.js", "MySQL", "Knex"],
      image: "/images/instock.png",
      github: "https://github.com/olivia-onuk/instock-full-stack-attack",
      responsibilities: [
        "Led frontend: pixel-perfect responsive design and interactive modals",
        "Built backend REST API with Node.js, Express, and MySQL via Knex; designed schema for fuzzy search, sorting, and bulk operations",
        "Conducted code reviews; earned 98.5% project score for code quality and teamwork",
      ],
      videoUrl: "/videos/instock.mp4",
    },
  ];